name: Discord_Webhook

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  WH:
    runs-on: ubuntu-latest
    steps:
      - name: Save commit message and description
        shell: bash
        env:
          COMMIT_MESSAGE: "${{ github.event.commits[0].message }}"
        run: |
          TITLE=$(echo "$COMMIT_MESSAGE" | sed -n '1p')
          DESCRIPTION=$(echo "$COMMIT_MESSAGE" | sed -n '3,$p')
          
          echo "TITLE=${TITLE}" >> $GITHUB_ENV
          echo "DESCRIPTION<<EOF" >> $GITHUB_ENV
          echo "$DESCRIPTION" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Sending message
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DESCRIPTION: ${{ env.DESCRIPTION }}
          DATA:
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "username": "GitHub_${{ github.event.commits[0].author.name }}",
                 "embeds": [
                   {
                     "title": "'"${{ env.TITLE }}"'",
                     "description": '"$(echo "$DESCRIPTION" | jq -Rs .)"',
                     "url": "https://github.com/${{ github.repository }}/actions"
                   }
                 ]
               }' \
               $WEBHOOK_URL
