name: Discord_Webhook

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  WH:
    runs-on: ubuntu-latest
    steps:
      - env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DATA:
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "username": "GitHub",
                 "embeds": [
                   {
                     "title": "GitHub Actions Notification",
                     "description": "Action details or summary here",
                     "url": "https://github.com/${{ github.repository }}/actions"
                   }
                 ]
               }' \
               $WEBHOOK_URL
               