name: Test notification

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.job}}
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Commit message:${{github.event.commits[0].message}}"

  event_log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event) }}"
