name: Test notification

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.job}}
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.head_commit.message}}
  test3:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.head_commit.author.name}}
